import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="pl">
            <head>
                <title>Strefa Klienta</title>
                <link rel="icon" href="../images/fav.jpg" />
            </head>
            <body className={`${inter.className} max-h-screen overflow-hidden bg-black text-white`}>
                <div className="fixed top-0 left-0 bg-gradient-to-b from-slate-100/20 to-white/0 w-full lg:h-[50vh] -z-50" />
                <div className="overflow-hidden w-full h-full">
                    <div className="lg:w-full w-80 h-1/2 rotate-45 rounded-xl bg-gradient-to-tr from-gray-200/90 absolute top-0 left-0 shadow-xl -z-10" />
                </div>
                <main className="mt-20 min-h-screen overflow-hidden">
                    {children}
                </main>
            </body>
        </html>
    );
}
