import { Inter } from "next/font/google";
import "../styles/globals.css";
import Header from "./Header";
import Footer from "./Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="pl">
            <head>
                <title>Fotograf</title>
                <link rel="icon" href="../images/fav.jpg" />
            </head>
            <body className={inter.className}>
                <div className="fixed top-0 left-0 bg-gradient-to-b from-slate-700/20 to-white/0 w-full lg:h-[50vh] -z-50" />
                <Header />
                <main className="mt-20">{children}</main>
                <Footer />
            </body>
        </html>
    );
}
