// import { Inter } from "next/font/google";
import "../styles/globals.css";
import Header from "./Header";
import Footer from "./Footer";
import EffectBg from "./EffectBg";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="pl">
            <head>
                <title>Fotograf</title>
                <link rel="icon" href="../images/fav.jpg" />
            </head>
            <body className="relative w-full">
                <EffectBg />
                <Header />
                <main className="lg:mt-20 mt-10 min-h-screen w-full overflow-hidden">
                    {children}
                </main>
                <Footer />
            </body>
        </html>
    );
}
